[2023-10-17T16:09:24.346+0000] {processor.py:157} INFO - Started process (PID=32) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:09:24.349+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:09:24.353+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:09:24.353+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:09:24.397+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:09:24.394+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:09:24.398+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:09:24.411+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.068 seconds
[2023-10-17T16:09:54.621+0000] {processor.py:157} INFO - Started process (PID=40) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:09:54.624+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:09:54.627+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:09:54.627+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:09:54.647+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:09:54.644+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:09:54.649+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:09:54.663+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.044 seconds
[2023-10-17T16:10:25.199+0000] {processor.py:157} INFO - Started process (PID=47) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:10:25.201+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:10:25.203+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:10:25.203+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:10:25.226+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:10:25.223+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:10:25.228+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:10:25.243+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.047 seconds
[2023-10-17T16:10:55.757+0000] {processor.py:157} INFO - Started process (PID=55) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:10:55.759+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:10:55.762+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:10:55.761+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:10:55.781+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:10:55.778+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:10:55.782+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:10:55.798+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.044 seconds
[2023-10-17T16:11:26.184+0000] {processor.py:157} INFO - Started process (PID=63) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:11:26.188+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:11:26.190+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:11:26.190+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:11:26.213+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:11:26.210+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:11:26.215+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:11:26.228+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.048 seconds
[2023-10-17T16:11:56.770+0000] {processor.py:157} INFO - Started process (PID=72) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:11:56.772+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:11:56.775+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:11:56.775+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:11:56.795+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:11:56.793+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:11:56.798+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:11:56.811+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.045 seconds
[2023-10-17T16:12:27.380+0000] {processor.py:157} INFO - Started process (PID=80) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:12:27.382+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:12:27.385+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:12:27.385+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:12:27.408+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:12:27.404+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:12:27.409+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:12:27.424+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.048 seconds
[2023-10-17T16:12:57.881+0000] {processor.py:157} INFO - Started process (PID=88) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:12:57.882+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:12:57.885+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:12:57.885+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:12:57.905+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:12:57.902+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:12:57.907+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:12:57.920+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.043 seconds
[2023-10-17T16:13:28.300+0000] {processor.py:157} INFO - Started process (PID=96) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:13:28.302+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:13:28.304+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:13:28.304+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:13:28.326+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:13:28.323+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:13:28.328+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:13:28.343+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.046 seconds
[2023-10-17T16:13:58.871+0000] {processor.py:157} INFO - Started process (PID=104) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:13:58.873+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:13:58.876+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:13:58.876+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:13:58.898+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:13:58.895+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:13:58.900+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:13:58.914+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.047 seconds
[2023-10-17T16:14:29.541+0000] {processor.py:157} INFO - Started process (PID=112) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:14:29.543+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:14:29.546+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:14:29.546+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:14:29.568+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:14:29.565+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:14:29.569+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:14:29.584+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.045 seconds
[2023-10-17T16:14:59.928+0000] {processor.py:157} INFO - Started process (PID=120) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:14:59.930+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:14:59.933+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:14:59.933+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:14:59.953+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:14:59.950+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:14:59.956+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:14:59.971+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.046 seconds
[2023-10-17T16:29:00.343+0000] {processor.py:157} INFO - Started process (PID=32) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:29:00.346+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:29:00.348+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:29:00.348+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:29:00.371+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:29:00.366+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:29:00.373+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:29:00.389+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.049 seconds
[2023-10-17T16:29:30.785+0000] {processor.py:157} INFO - Started process (PID=40) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:29:30.787+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:29:30.789+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:29:30.789+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:29:30.809+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:29:30.807+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:29:30.811+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:29:30.825+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.043 seconds
[2023-10-17T16:30:01.189+0000] {processor.py:157} INFO - Started process (PID=48) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:30:01.192+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:30:01.196+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:30:01.196+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:30:01.218+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:30:01.216+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:30:01.220+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:30:01.236+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.050 seconds
[2023-10-17T16:30:31.697+0000] {processor.py:157} INFO - Started process (PID=57) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:30:31.700+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:30:31.702+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:30:31.702+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:30:31.723+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:30:31.720+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:30:31.725+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:30:31.738+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.044 seconds
[2023-10-17T16:31:02.356+0000] {processor.py:157} INFO - Started process (PID=65) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:31:02.358+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:31:02.360+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:31:02.360+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:31:02.383+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:31:02.380+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:31:02.384+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:31:02.400+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.047 seconds
[2023-10-17T16:31:32.810+0000] {processor.py:157} INFO - Started process (PID=73) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:31:32.813+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:31:32.816+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:31:32.816+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:31:32.836+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:31:32.833+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:31:32.838+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:31:32.852+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.045 seconds
[2023-10-17T16:32:03.233+0000] {processor.py:157} INFO - Started process (PID=81) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:32:03.235+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:32:03.238+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:32:03.238+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:32:03.260+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:32:03.257+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:32:03.261+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:32:03.277+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.047 seconds
[2023-10-17T16:32:33.850+0000] {processor.py:157} INFO - Started process (PID=89) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:32:33.853+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:32:33.856+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:32:33.856+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:32:33.882+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:32:33.879+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:32:33.884+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:32:33.899+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.053 seconds
[2023-10-17T16:33:04.416+0000] {processor.py:157} INFO - Started process (PID=97) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:33:04.419+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:33:04.421+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:33:04.421+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:33:04.443+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:33:04.439+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:33:04.444+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:33:04.458+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.045 seconds
[2023-10-17T16:33:34.866+0000] {processor.py:157} INFO - Started process (PID=104) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:33:34.868+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:33:34.871+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:33:34.871+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:33:34.895+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:33:34.891+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:33:34.896+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:33:34.910+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.048 seconds
[2023-10-17T16:34:05.275+0000] {processor.py:157} INFO - Started process (PID=112) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:34:05.277+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:34:05.281+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:34:05.281+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:34:05.308+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:34:05.304+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:34:05.311+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:34:05.326+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.054 seconds
[2023-10-17T16:34:35.743+0000] {processor.py:157} INFO - Started process (PID=120) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:34:35.744+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:34:35.747+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:34:35.747+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:34:35.767+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:34:35.763+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:34:35.768+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:34:35.786+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.046 seconds
[2023-10-17T16:35:06.197+0000] {processor.py:157} INFO - Started process (PID=128) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:35:06.199+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:35:06.202+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:35:06.202+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:35:06.222+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:35:06.219+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:35:06.224+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:35:06.241+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.046 seconds
[2023-10-17T16:35:36.637+0000] {processor.py:157} INFO - Started process (PID=135) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:35:36.639+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:35:36.642+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:35:36.642+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:35:36.663+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:35:36.661+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:35:36.666+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:35:36.682+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.049 seconds
[2023-10-17T16:36:07.121+0000] {processor.py:157} INFO - Started process (PID=142) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:36:07.123+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:36:07.125+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:36:07.125+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:36:07.148+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:36:07.145+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:36:07.149+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:36:07.164+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.047 seconds
[2023-10-17T16:36:37.560+0000] {processor.py:157} INFO - Started process (PID=150) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:36:37.562+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:36:37.565+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:36:37.565+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:36:37.588+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:36:37.585+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:36:37.589+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:36:37.604+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.047 seconds
[2023-10-17T16:37:08.046+0000] {processor.py:157} INFO - Started process (PID=158) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:37:08.049+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:37:08.052+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:37:08.052+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:37:08.075+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:37:08.072+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:37:08.078+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:37:08.096+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.054 seconds
[2023-10-17T16:37:38.508+0000] {processor.py:157} INFO - Started process (PID=166) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:37:38.511+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:37:38.514+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:37:38.513+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:37:38.533+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:37:38.530+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:37:38.535+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:37:38.551+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.045 seconds
[2023-10-17T16:38:08.963+0000] {processor.py:157} INFO - Started process (PID=174) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:38:08.966+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:38:08.970+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:38:08.969+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:38:08.994+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:38:08.991+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:38:08.996+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:38:09.011+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.051 seconds
[2023-10-17T16:38:39.437+0000] {processor.py:157} INFO - Started process (PID=182) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:38:39.440+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:38:39.444+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:38:39.443+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:38:39.472+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:38:39.468+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:38:39.474+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:38:39.488+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.056 seconds
[2023-10-17T16:39:09.909+0000] {processor.py:157} INFO - Started process (PID=191) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:39:09.912+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:39:09.915+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:39:09.915+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:39:09.938+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:39:09.936+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:39:09.940+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:39:09.956+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.050 seconds
[2023-10-17T16:39:40.388+0000] {processor.py:157} INFO - Started process (PID=199) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:39:40.390+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:39:40.394+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:39:40.393+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:39:40.417+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:39:40.414+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:39:40.419+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:39:40.435+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.050 seconds
[2023-10-17T16:40:10.877+0000] {processor.py:157} INFO - Started process (PID=208) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:40:10.880+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:40:10.884+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:40:10.884+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:40:10.905+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:40:10.901+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:40:10.907+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:40:10.922+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.048 seconds
[2023-10-17T16:40:41.482+0000] {processor.py:157} INFO - Started process (PID=215) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:40:41.484+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:40:41.487+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:40:41.486+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:40:41.505+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:40:41.502+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:40:41.507+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:40:41.520+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.040 seconds
[2023-10-17T16:41:11.883+0000] {processor.py:157} INFO - Started process (PID=223) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:41:11.885+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:41:11.887+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:41:11.887+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:41:11.907+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:41:11.903+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:41:11.908+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:41:11.922+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.042 seconds
[2023-10-17T16:41:42.424+0000] {processor.py:157} INFO - Started process (PID=231) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:41:42.425+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:41:42.428+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:41:42.428+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:41:42.449+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:41:42.446+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:41:42.450+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:41:42.465+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.044 seconds
[2023-10-17T16:42:12.873+0000] {processor.py:157} INFO - Started process (PID=239) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:42:12.876+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T16:42:12.879+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:42:12.879+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:42:12.902+0000] {logging_mixin.py:151} INFO - [2023-10-17T16:42:12.898+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T16:42:12.903+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T16:42:12.919+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.049 seconds
[2023-10-17T17:16:08.113+0000] {processor.py:157} INFO - Started process (PID=32) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:16:08.116+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:16:08.118+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:16:08.118+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:16:08.145+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:16:08.141+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:16:08.147+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:16:08.164+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.054 seconds
[2023-10-17T17:16:38.419+0000] {processor.py:157} INFO - Started process (PID=40) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:16:38.422+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:16:38.424+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:16:38.424+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:16:38.448+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:16:38.444+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:16:38.450+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:16:38.467+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.051 seconds
[2023-10-17T17:17:08.872+0000] {processor.py:157} INFO - Started process (PID=48) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:17:08.874+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:17:08.876+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:17:08.876+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:17:08.895+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:17:08.892+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:17:08.897+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:17:08.912+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.043 seconds
[2023-10-17T17:17:39.391+0000] {processor.py:157} INFO - Started process (PID=56) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:17:39.394+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:17:39.398+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:17:39.398+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:17:39.423+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:17:39.419+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:17:39.426+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:17:39.440+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.054 seconds
[2023-10-17T17:18:09.950+0000] {processor.py:157} INFO - Started process (PID=64) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:18:09.952+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:18:09.956+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:18:09.955+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:18:09.982+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:18:09.979+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:18:09.984+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:18:09.998+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.053 seconds
[2023-10-17T17:18:40.438+0000] {processor.py:157} INFO - Started process (PID=72) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:18:40.441+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:18:40.443+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:18:40.443+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:18:40.465+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:18:40.462+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:18:40.466+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:18:40.482+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.046 seconds
[2023-10-17T17:19:10.845+0000] {processor.py:157} INFO - Started process (PID=80) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:19:10.849+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:19:10.854+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:19:10.853+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:19:10.877+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:19:10.874+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:19:10.880+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:19:10.893+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.052 seconds
[2023-10-17T17:19:41.253+0000] {processor.py:157} INFO - Started process (PID=87) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:19:41.256+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:19:41.259+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:19:41.259+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:19:41.282+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:19:41.279+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:19:41.284+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:19:41.301+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.051 seconds
[2023-10-17T17:20:11.681+0000] {processor.py:157} INFO - Started process (PID=95) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:20:11.684+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:20:11.688+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:20:11.687+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:20:11.712+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:20:11.708+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:20:11.714+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:20:11.728+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.049 seconds
[2023-10-17T17:20:42.095+0000] {processor.py:157} INFO - Started process (PID=103) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:20:42.097+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:20:42.099+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:20:42.099+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:20:42.119+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:20:42.116+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:20:42.123+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:20:42.137+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.045 seconds
[2023-10-17T17:21:12.520+0000] {processor.py:157} INFO - Started process (PID=110) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:21:12.522+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:21:12.526+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:21:12.526+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:21:12.552+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:21:12.548+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:21:12.554+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:21:12.572+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.054 seconds
[2023-10-17T17:21:42.945+0000] {processor.py:157} INFO - Started process (PID=119) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:21:42.946+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:21:42.949+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:21:42.949+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:21:42.970+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:21:42.967+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:21:42.972+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:21:42.987+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.045 seconds
[2023-10-17T17:22:13.306+0000] {processor.py:157} INFO - Started process (PID=127) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:22:13.308+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:22:13.311+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:22:13.311+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:22:13.331+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:22:13.328+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:22:13.333+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:22:13.348+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.045 seconds
[2023-10-17T17:22:43.850+0000] {processor.py:157} INFO - Started process (PID=135) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:22:43.852+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:22:43.855+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:22:43.855+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:22:43.875+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:22:43.872+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:22:43.877+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:22:43.891+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.044 seconds
[2023-10-17T17:23:14.347+0000] {processor.py:157} INFO - Started process (PID=143) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:23:14.350+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:23:14.353+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:23:14.353+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:23:14.377+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:23:14.374+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:23:14.380+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:23:14.396+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.052 seconds
[2023-10-17T17:24:27.093+0000] {processor.py:157} INFO - Started process (PID=32) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:24:27.095+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:24:27.098+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:24:27.098+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:24:27.121+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:24:27.118+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:24:27.122+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:24:27.137+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.047 seconds
[2023-10-17T17:24:57.441+0000] {processor.py:157} INFO - Started process (PID=40) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:24:57.443+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:24:57.445+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:24:57.445+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:24:57.466+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:24:57.462+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:24:57.467+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:24:57.483+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.045 seconds
[2023-10-17T17:25:27.857+0000] {processor.py:157} INFO - Started process (PID=48) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:25:27.859+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:25:27.862+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:25:27.861+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:25:27.881+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:25:27.878+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:25:27.883+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:25:27.900+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.045 seconds
[2023-10-17T17:25:58.363+0000] {processor.py:157} INFO - Started process (PID=56) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:25:58.366+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:25:58.370+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:25:58.369+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:25:58.395+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:25:58.392+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:25:58.397+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:25:58.411+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.052 seconds
[2023-10-17T17:26:28.865+0000] {processor.py:157} INFO - Started process (PID=64) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:26:28.867+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:26:28.871+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:26:28.870+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:26:28.892+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:26:28.888+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:26:28.893+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:26:28.908+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.045 seconds
[2023-10-17T17:26:59.309+0000] {processor.py:157} INFO - Started process (PID=72) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:26:59.311+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:26:59.314+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:26:59.314+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:26:59.336+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:26:59.333+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:26:59.340+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:26:59.358+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.051 seconds
[2023-10-17T17:27:29.787+0000] {processor.py:157} INFO - Started process (PID=80) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:27:29.789+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:27:29.792+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:27:29.792+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:27:29.814+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:27:29.810+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:27:29.815+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:27:29.832+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.047 seconds
[2023-10-17T17:28:00.183+0000] {processor.py:157} INFO - Started process (PID=88) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:28:00.184+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:28:00.187+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:28:00.187+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:28:00.208+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:28:00.205+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:28:00.210+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:28:00.224+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.044 seconds
[2023-10-17T17:28:30.561+0000] {processor.py:157} INFO - Started process (PID=96) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:28:30.563+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:28:30.566+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:28:30.565+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:28:30.586+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:28:30.583+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:28:30.588+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:28:30.604+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.045 seconds
[2023-10-17T17:29:00.886+0000] {processor.py:157} INFO - Started process (PID=104) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:29:00.888+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:29:00.892+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:29:00.892+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:29:00.915+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:29:00.911+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:29:00.917+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:29:00.941+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.058 seconds
[2023-10-17T17:29:31.277+0000] {processor.py:157} INFO - Started process (PID=112) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:29:31.279+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:29:31.281+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:29:31.281+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:29:31.302+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:29:31.298+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:29:31.303+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:29:31.318+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.044 seconds
[2023-10-17T17:30:01.673+0000] {processor.py:157} INFO - Started process (PID=121) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:30:01.675+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:30:01.677+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:30:01.677+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:30:01.695+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:30:01.693+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:30:01.698+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:30:01.712+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.041 seconds
[2023-10-17T17:30:32.165+0000] {processor.py:157} INFO - Started process (PID=129) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:30:32.168+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:30:32.171+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:30:32.171+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:30:32.193+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:30:32.190+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:30:32.194+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:30:32.209+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.047 seconds
[2023-10-17T17:31:02.672+0000] {processor.py:157} INFO - Started process (PID=138) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:31:02.674+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:31:02.677+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:31:02.677+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:31:02.696+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:31:02.693+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:31:02.698+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:31:02.713+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.043 seconds
[2023-10-17T17:31:33.142+0000] {processor.py:157} INFO - Started process (PID=146) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:31:33.144+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:31:33.146+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:31:33.146+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:31:33.170+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:31:33.166+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:31:33.172+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:31:33.187+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.048 seconds
[2023-10-17T17:32:03.689+0000] {processor.py:157} INFO - Started process (PID=154) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:32:03.691+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:32:03.694+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:32:03.694+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:32:03.714+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:32:03.711+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:32:03.716+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:32:03.731+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.044 seconds
[2023-10-17T17:32:34.189+0000] {processor.py:157} INFO - Started process (PID=162) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:32:34.191+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:32:34.193+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:32:34.193+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:32:34.214+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:32:34.211+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:32:34.216+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:32:34.232+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.046 seconds
[2023-10-17T17:33:04.607+0000] {processor.py:157} INFO - Started process (PID=171) to work on /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:33:04.610+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-10-17T17:33:04.613+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:33:04.613+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:33:04.634+0000] {logging_mixin.py:151} INFO - [2023-10-17T17:33:04.632+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-10-17T17:33:04.636+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-10-17T17:33:04.650+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.047 seconds
