[2023-09-29T00:00:12.051+0000] {processor.py:157} INFO - Started process (PID=65) to work on /opt/airflow/dags/automate_archival_description.py
[2023-09-29T00:00:12.052+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-09-29T00:00:12.055+0000] {logging_mixin.py:151} INFO - [2023-09-29T00:00:12.055+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-09-29T00:00:12.075+0000] {logging_mixin.py:151} INFO - [2023-09-29T00:00:12.073+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-09-29T00:00:12.078+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-09-29T00:00:12.092+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.045 seconds
[2023-09-29T00:00:42.492+0000] {processor.py:157} INFO - Started process (PID=73) to work on /opt/airflow/dags/automate_archival_description.py
[2023-09-29T00:00:42.494+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-09-29T00:00:42.497+0000] {logging_mixin.py:151} INFO - [2023-09-29T00:00:42.496+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-09-29T00:00:42.519+0000] {logging_mixin.py:151} INFO - [2023-09-29T00:00:42.516+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-09-29T00:00:42.521+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-09-29T00:00:42.535+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.046 seconds
[2023-09-29T00:01:12.914+0000] {processor.py:157} INFO - Started process (PID=81) to work on /opt/airflow/dags/automate_archival_description.py
[2023-09-29T00:01:12.916+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-09-29T00:01:12.920+0000] {logging_mixin.py:151} INFO - [2023-09-29T00:01:12.919+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-09-29T00:01:12.946+0000] {logging_mixin.py:151} INFO - [2023-09-29T00:01:12.943+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-09-29T00:01:12.948+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-09-29T00:01:12.966+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.055 seconds
[2023-09-29T00:01:43.323+0000] {processor.py:157} INFO - Started process (PID=88) to work on /opt/airflow/dags/automate_archival_description.py
[2023-09-29T00:01:43.325+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-09-29T00:01:43.328+0000] {logging_mixin.py:151} INFO - [2023-09-29T00:01:43.328+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-09-29T00:01:43.347+0000] {logging_mixin.py:151} INFO - [2023-09-29T00:01:43.344+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-09-29T00:01:43.349+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-09-29T00:01:43.365+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.045 seconds
[2023-09-29T00:02:13.678+0000] {processor.py:157} INFO - Started process (PID=96) to work on /opt/airflow/dags/automate_archival_description.py
[2023-09-29T00:02:13.680+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/automate_archival_description.py for tasks to queue
[2023-09-29T00:02:13.684+0000] {logging_mixin.py:151} INFO - [2023-09-29T00:02:13.684+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/automate_archival_description.py
[2023-09-29T00:02:13.716+0000] {logging_mixin.py:151} INFO - [2023-09-29T00:02:13.712+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/automate_archival_description.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automate_archival_description.py", line 8, in <module>
    from asnake.client import ASnakeClient
ModuleNotFoundError: No module named 'asnake'
[2023-09-29T00:02:13.718+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/automate_archival_description.py
[2023-09-29T00:02:13.737+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/automate_archival_description.py took 0.062 seconds
